# Generated by Django 5.0.4 on 2024-04-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
