# Generated by Django 5.0.4 on 2024-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('short', '0002_delete_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('details', models.TextField()),
                ('image_hash', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
