# Generated by Django 5.0.4 on 2024-04-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_imageupload_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image_hash',
        ),
    ]
